import Head from 'next/head'
import Image from 'next/image'
// import Button from '../components/ButtonComp'
import styles from '../styles/ComingSoon.module.css'
import Link from 'next/link'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Input from '../components/KingInput'
import { FaFacebookF, FaTwitter, FaYoutube, FaDribbble } from 'react-icons/fa';

export default function ComingSoon() {
  return(
    <div>
    <Navbar/>
      <Head>
        <title> The King | Coming Soon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className='Notfound bg-color1'>
        <header className='container'>
            <div className='row align-items-center'>
              <div className={`${styles.left} col-12 col-lg-6`}>
                <h1 className={`${styles.headText} fs-1`}><span className='text-light'>We’re Building Something New</span></h1>
                <div className="row">
                    <div className={`${styles.timeText} col`}>09</div>
                    <div className={`${styles.timeText} col`}>18</div>
                    <div className={`${styles.timeText} col`}>37</div>
                    <div className={`${styles.timeText} col`}>56</div>
                </div>
                <div className="row">
                    <div className={`${styles.desText} col`}>Days</div>
                    <div className={`${styles.desText} col`}>Hours</div>
                    <div className={`${styles.desText} col`}>Mins</div>
                    <div className={`${styles.desText} col`}>Sec</div>
                </div>
              </div>
              <div className={`${styles.right} col-12 col-lg-6`}>
                <div className='mx-auto text-center mt-4'>
                </div>
              </div>
            </div>
        </header>
        </main>
        <footer className='bg-color1'>
        <div className='container'>
        <div className="row row-cols-3">
            <div className="col mb-4">
            <Image layout='intrinsic' alt='logo' src='/images/logo.png' width={70} height={70} />
            </div>
            <div className="col text-center text-light">The King Furniture is a shop that sells a variety of your home furniture needs.</div>
            <div className="col d-flex flex-row">
            <div className='ms-lg-3 px-2 text-light'>
                <FaFacebookF />
              </div>
              <div className='ms-lg-3 px-2 text-light'>
                <FaTwitter/>
              </div>
              <div className='ms-lg-3 px-2 text-light'>
                <FaYoutube/>
              </div>
              <div className='ms-lg-3 px-2 text-light'>
                <FaDribbble/>
              </div>
            </div>
            </div>
        </div>
        </footer>
    </div>
  )
}
