import { Col, Row, Container, Form } from 'react-bootstrap'
import Head from 'next/head'
import styles from '../styles/Auth.module.scss'
import { useDispatch, useSelector } from 'react-redux'
import { forgot } from '../redux/actions/auth'
import Layout from '../components/Layout'
import { Alert } from 'react-bootstrap'

const Forgotpassword = () => {

  const { auth } = useSelector(state => state)
  const dispatch = useDispatch()

  const onForgot = (e) => {
    e.preventDefault()
    const email = e.target.elements['email'].value
    dispatch(forgot(email))
  }
  return (
    <>
      <Layout>
        <Head>
          <title>The King | Forgot Password</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`${styles.profiles} `}>
          <div className="d-flex flex-column justify-content-center">
            <h1 className={`${styles.content} text-center mb-1 mt-5`}>My Account</h1>
            <h5 className={`${styles.content} text-center mb-5`}>Register and log in with your account to be able to shop at will</h5>
          </div>
        </div>
        <Container>
          <Row className='justify-content-center mt-5'>
            <Col xl={6} className='d-flex flex-column'>
              {auth.isErr && <Alert variant="danger" className='text-center'>{auth.errMsg}</Alert>}
              {auth.successMsg && <Alert variant='success' className='text-center'>{auth.successMsg}</Alert>}
            </Col>
          </Row>
          <Row>
            <Col xl={3}></Col>
            <Col xl={6}>
              <Row className='mt-4 px-5'>
                <Col xl={12} className='mb-4'>
                  <div>
                    <h3>Forgot your Password?</h3>
                  </div>
                  <div>
                    <p>Don’t worry! Just fill in your email and we’ll send you a link</p>
                  </div>
                </Col>
                <Form onSubmit={onForgot}>
                  <Col xl={12} className='mb-4'>
                    <div>
                      <input type='email' name='email' className='w-100 px-4 py-3' placeholder='Your email address'></input>
                    </div>
                  </Col>
                  <Col xl={12} className='mb-5'>
                    <div>
                      <button type='submit' className={`${styles.button} px-4 py-3`}>Reset Password</button>
                    </div>
                  </Col>
                </Form>
              </Row>
            </Col>
            <Col xl={3}></Col>
          </Row>
        </Container >
      </Layout>
    </>
  )
}

export default Forgotpassword