import { Col, Row, Container, Form } from 'react-bootstrap'
import Head from 'next/head'
import styles from '../styles/Auth.module.scss'
import { useDispatch } from 'react-redux'
import { forgot } from '../redux/actions/auth'

const Forgot = () => {

  const dispatch = useDispatch

  const onForgot = (e) => {
    e.preventDefault()
    const email = e.target.elements['email'].value

    dispatch(forgot(email))
    alert('Please check your email, we have sent you a link!')
  }
  return (
    <>
      <Head>
        <title>The King | Forgot Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row>
          <Col xl={12} className='text-center mt-5 mb-5'>
            <h1 className='fs-1 text-bold'>MyAccount</h1>
            <h5>Register and log in with your account to be able to shop at will</h5>
          </Col>
        </Row>
        <Row>
          <Col xl={3}></Col>
          <Col xl={6}>
            <Row className='mt-4 px-5'>
              <Col xl={12} className='mb-4'>
                <div>
                  <h3>Forgot your Password?</h3>
                </div>
                <div>
                  <p>Don’t worry! Just fill in your email and we’ll send you a link</p>
                </div>
              </Col>
              <Form onSubmit={onForgot}>
                <Col xl={12} className='mb-4'>
                  <div>
                    <input name='email' className='w-100 px-4 py-3' placeholder='Your email address'></input>
                  </div>
                </Col>
                <Col xl={12} className='mb-5'>
                  <div>
                    <button type='submit' className={`${styles.button} px-4 py-3`}>Reset Password</button>
                  </div>
                </Col>
              </Form>
            </Row>
          </Col>
          <Col xl={3}></Col>
        </Row>
      </Container >
    </>
  )
}

export default Forgot