import { Col, Row, Container, Form } from 'react-bootstrap'
import Head from 'next/head'
import styles from '../styles/Auth.module.scss'
import Link from "next/link"

const LoginRegister = () => {
  return (
    <>
      <Head>
        <title>The King | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row>
          <Col xl={12} className='text-center mt-5 mb-5'>
            <h1 className='fs-1 text-bold'>MyAccount</h1>
            <h5>Register and log in with your account to be able to shop at will</h5>
          </Col>
        </Row>
        <Row>
          <Col xl={6}>
            <Row className='mt-4 px-5'>
              <Col xl={12} className='mb-5'>
                <div>
                  <h3>Login</h3>
                </div>
              </Col>
              <Col xl={12} className='mb-3'>
                <div>
                  <input className='w-100 px-4 py-3' placeholder='Username or email address'></input>
                </div>
              </Col>
              <Col xl={12} className='mb-4'>
                <div>
                  <input className='w-100 px-4 py-3' placeholder='Password'></input>
                </div>
              </Col>
              <Col xl={12} className='mb-5'>
                <div>
                  <button className={`${styles.button} px-5 py-3`}>Login</button>
                </div>
              </Col>
              <Col xl={12}>
                <Row>
                  <Col xl={4}>
                    <div className="form-check">
                      <input className="form-check-input" type="checkbox" value="" id="flexCheckChecked" />
                      <label className="form-check-label" htmlFor="flexCheckChecked">Remember me</label>
                    </div>
                  </Col>
                  <Col xl={6}>
                    <Link href="/Forgot">
                      <a className='text-danger'>Forgot your password</a>
                    </Link>
                  </Col>
                </Row>
              </Col>
            </Row>
          </Col>
          <Col xl={6}>
            <Row className='mt-4 px-5'>
              <Col xl={12} className='mb-5'>
                <div>
                  <h3>Create Account</h3>
                </div>
              </Col>
              <Col xl={12} className='mb-3'>
                <div>
                  <input className='w-100 px-4 py-3' placeholder='Email address'></input>
                </div>
              </Col>
              <Col xl={12} className='mb-4'>
                <div>
                  <input className='w-100 px-4 py-3' placeholder='Password'></input>
                </div>
              </Col>
              <Col xl={12} className='mb-4'>
                <div className='d-flex'>
                  <div className='me-5'>
                    <label className='position-relative align-items-center d-flex'>
                      <input type="radio" className='position-absolute' name="role" />
                      <div className="d-inline-block"></div>
                      <div className="text d-inline-block ms-4">I`m Customer</div>
                    </label>
                  </div>
                  <div className='me-5'>
                    <label className='position-relative align-items-center d-flex'>
                      <input type="radio" className='position-absolute' name="role" />
                      <div className="d-inline-block"></div>
                      <div className="text d-inline-block ms-4">I`m Seller</div>
                    </label>
                  </div>
                </div>
              </Col>
              <Col xl={12}>
                <div>
                  <button className={`${styles.button} px-5 py-3`}>Register</button>
                </div>
              </Col>
            </Row>
          </Col>
        </Row>
      </Container >
    </>
  )
}

export default LoginRegister