import Image from "next/image";
import { Row, Col, Container } from "react-bootstrap";
import Layout from "../components/Layout"
import NavbarProfile from "../components/NavbarProfile";
import { BsCheck } from 'react-icons/bs';
import styles from '../styles/profile.module.scss';
import Head from "next/head";
import { getTransactionSeller } from "../redux/actions/transactionSeller";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { getProfile } from "../redux/actions/auth";
import empty from "../public/images/empty-input-image.png"
import NumberFormat from "react-number-format";

const MyOrder = () => {
  const {auth, transactionSeller} = useSelector(state=>state)
  const dispatch = useDispatch()

  // useEffect(()=>{
  //   const token = window.localStorage.getItem('token')
  //   if (token) {
  //     dispatch(getTransactionSeller(token))
  //   }    
  // },[dispatch])

  useEffect(()=>{
    if (auth.userData?.id) {
      const token = window.localStorage.getItem('token')
      dispatch(getTransactionSeller(token))
    }
  },[auth.userData.id])

  useEffect(()=>{
    dispatch(getProfile)
  },[])

  const formatter = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  });

  return (
    <Layout>
            <Head>
            <title>The King | My Order</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`${styles.containers} `}>
                <div className={`${styles.profiles} `}>
                    <div className="d-flex flex-column justify-content-center vh-50">
                        <div className={`${styles.content} text-center mt-4`}>My Order</div>
                        <div className={`${styles.contents} text-center mb-5`}>See your notifications for the latest updates</div>
                    </div>
                </div>
                <div className="d-flex justify-content-center align-items-center px-5 mx-5">                    
                    <NavbarProfile />    
                </div>
                <Container>
                <Row className="pb-2 pt-5 text-muted d-none d-lg-flex">
          <Col lg={4}>
            <span>Products</span>
          </Col>
          <Col lg={2}>
            <span>Price</span>
          </Col>
          <Col lg={2}>
            <span>Quantity</span>
          </Col>
          <Col lg={2}>
            <span>Status Order</span>
          </Col>
          <Col lg={2}>
            <span>Total</span>
          </Col>
        </Row>
        {transactionSeller?.data && <div>
        {transactionSeller?.data.map((datas, index) => {
          return (
            <Row key={datas.id} className='my-5'>
              <Col lg={4}>
                <div className='d-flex flex-row align-items-center'>
                  <Image src={datas.product.product_images[0]?.image ? datas.product.product_images[0]?.image : empty} width={100} height={100} alt='Product picture' />
                  <span className="ms-5">{datas.product?.name ? datas.product?.name : ' '}</span>
                </div>
              </Col>
              <Col xs={6} lg={2} className='my-auto mt-4 mt-lg-auto'>
                <div>
                  <span className="text-muted d-inline d-lg-none">Price: </span>
                  <span className="fw-bold"><NumberFormat value={datas?.total_price} displayType={'text'} thousandSeparator={'.'} decimalSeparator={','} prefix={'Rp. '} ></NumberFormat></span>
                </div>
              </Col>
              <Col xs={6} lg={2} className='my-auto mt-4 mt-lg-auto'>
                <span className="text-muted d-inline d-lg-none">Qty: </span>
                <span>{datas.qty < 10 ? '0'+datas.qty : datas.qty}</span>
              </Col>
              <Col xs={6} lg={2} className='my-auto mt-4 mt-lg-auto'>
                <div>
                  <span className="text-muted d-inline d-lg-none">Status order: </span>
                  <span className={styles.pill}><BsCheck/></span> {datas.transaction_status.name}
                </div>
              </Col>
              <Col xs={6} lg={2} className='my-auto mt-4 mt-lg-auto'>
                <span className="text-muted d-inline d-lg-none">Total: </span>
                <span className="fw-bold"><NumberFormat value={datas?.total_price} displayType={'text'} thousandSeparator={'.'} decimalSeparator={','} prefix={'Rp. '} ></NumberFormat></span>
              </Col>
            </Row>
          )
        })}
        </div>}
        <hr className="mb-5"/>
                </Container>
            </div>
    </Layout>
  )
}

export default MyOrder