import { Row, Col, Card, Container } from "react-bootstrap"
import styles from "../styles/profile.module.scss"
import Image from "next/image"
import NavbarProfile from "../components/NavbarProfile"
import Layout from "../components/Layout"
import Head from "next/head"
import Button from "../components/Button";
import { BsCheck } from 'react-icons/bs';
import { useDispatch, useSelector } from "react-redux"
import { useEffect, useState } from "react"
import { deleteProductSeller, getProductSeller } from "../redux/actions/productSeller"
import empty from "../public/images/empty-input-image.png"
import NumberFormat from "react-number-format"
import Modal from "../components/ModalDelete"
import React from "react"
import { useRouter } from "next/router"
import { getProfile } from "../redux/actions/auth"

const MyProduct = () => {
  
  const {auth, productSeller} = useSelector(state=>state)
  const dispatch = useDispatch()
  const [modalShow, setModalShow] = React.useState(false);
  const router = useRouter()
  const [token, setToken] = useState()

  useEffect(()=>{
    if (auth.userData?.id) {
      dispatch(getProductSeller(auth.userData?.id))
    }
  },[auth.userData.id])

  useEffect(()=>{
    dispatch(getProfile)
  },[])

  const deleteHandler = async ( id) => {
    const token = window.localStorage.getItem('token')
    await dispatch(deleteProductSeller(token, id))    
    window.scrollTo(0, 0)
    await dispatch(getProductSeller(auth.userData?.id))
  }

  return (
    <Layout>
        <Head>
        <title>The King | My Product</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={`${styles.containers}`}>
            <div className={`${styles.profiles} `}>
                <div className="d-flex flex-column justify-content-center vh-50">
                    <div className={`${styles.content} text-center mt-4`}>My Product</div>
                    <div className={`${styles.contents} text-center mb-5`}>See your notifications for the latest updates</div>
                </div>
            </div>
            <div className="d-flex justify-content-center align-items-center px-5 mx-5">                    
                <NavbarProfile />    
            </div>
            <Container>
            <Row className="border-bottom border-top py-3 fw-bold d-none d-lg-flex">
          <Col lg={4}>
            Product
          </Col>
          <Col lg={4}>
            <span className="ms-0 ms-lg-5">Stock Status</span>
          </Col>
          <Col lg={4}>
            <span className="ms-0 ms-lg-5">Price</span>
          </Col>
        </Row>
        {/* {productSeller?.data.length === 1 && <div className="d-flex justify-content-center align-items-center vh-100">There is No Data Product</div>} */}
        {productSeller?.data && <div>
        {productSeller?.data.map((datas, index) => {
          return (
            <Row key={datas?.id} className='my-5'>
              <Col xs={12} sm={6} lg={4} className='d-flex flex-row align-items-center'>
                <Image src={datas.product_images[0]?.image ? datas.product_images[0]?.image : empty} alt='product' width={100} height={100} />
                <span className="ps-4">{datas?.name}</span>
              </Col>
              <Col xs={12} sm={6} lg={4} className='my-auto'>
                <div className="my-3 my-lg-0 ms-0 ms-lg-5">
                  <span ><BsCheck/></span> {datas?.stock} Stock
                </div>
              </Col>
              <Col xs={12} sm={12} lg={4} className='my-auto d-flex align-items-center'>
                <div className="fw-bold ms-0 ms-lg-5"><NumberFormat value={datas?.price} displayType={'text'} thousandSeparator={'.'} decimalSeparator={','} prefix={'Rp. '} ></NumberFormat></div>
                <Button onClick={() => setModalShow(true)} className={`${styles.button} px-5 py-2 ms-5`} color='danger'>Delete</Button>
                <Modal show={modalShow} onClick={()=>deleteHandler(datas.id)} onHide={() => setModalShow(false)} />
                {}
              </Col>
            </Row>
          )
        })}
        </div>}
            </Container>
        </div>
    </Layout>
  )
}

export default MyProduct;